### ISSUE TITLE
metapackage obsolete?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-metapkg#6]
before the tutorial, the aiida metapackage hadn't been updated since the 1.0b3 release

just wondering whether we want to keep updating this or not.
We could also decide to make an  "aiid 1.0" release that simply tracks `aiida-core>=1.0.0b6,<2.0)`

Mentioning @giovannipizzi @sphuber for comment

**Comment by sphuber** [comment]
We already removed the `aiida-nwchem` and `aiida-ase` plugins so now the only added benefit is that it installs `aiida-quantumespresso` and `aiida-codtools`. Since installing those manually is now relatively easy through `pip` I am wondering what the added benefit is. Maybe with the meta-package we control the compatibility between core and the added plugins better. That is if we keep this up to date a bit better then in the recent past. Long story short, I am not completely sure :)

**Comment by giovannipizzi** [comment]
My suggestion is, if possible, to make `aiida` just an alias to `aiida-core` so we don't have to worry about updating it? Do you know if this is possible in PyPI? (mainly because people knowing about AiiDA will try to pip install `aiida` and not `aiida-core`?)

**Comment by ltalirz** [comment]
>  if possible, to make aiida just an alias to aiida-core so we don't have to worry about updating it

That would indeed be useful - I've checked and I didn't find a way to do this on PyPI.

We could of course make a 1.0 release of the aiida package that simply depends on `aiida-core>=1.0,<2.0` but this will show up in `pip freeze`  as
```
aiida==1.0.0
aiida-core==1.0.1
```
at some point.

**Comment by ltalirz** [comment]
The alternative is we keep mirroring the version in `aiida` for the moment and simply automate releases as much as possible using the "create PR" action in github actions
https://github.com/marketplace/actions/create-pull-request (triggered by new release of aiida-core)

**Comment by ltalirz** [comment]
@giovannipizzi @sphuber What do you prefer here:
do we introduce the `aiida-core>=1.0,<2.0` dependency
or do we want to keep it up to date (perhaps partly automated later on)

**Comment by sphuber** [comment]
if we do the former, what would be the version of `aiida`, just `1.0.0`? Trying to see if that would be weird if people install `aiida==1.0.0` and they get `aiida-core==1.7.3` at some point. If not weird, maybe that is the easiest option

**Comment by sphuber** [comment]
In fact thinking about it now, this is not even the biggest question/problem. Going back to what the point really is of this package. Installing `aiida-quantumespresso` and `aiida-codtools` manually is just two commands. If we remove them there is no point to the package anymore in any case. If we do keep them, then we also have to make sure that their versioning stays up to date. Now we are in control of their releases as well so we could make sure to not break backwards compatibility in minor versions, but you never know. Not sure yet, but I am leaning towards discontinuing the meta package

**Comment by ltalirz** [comment]
>  If we do keep them, then we also have to make sure that their versioning stays up to date.

I would say we all agree that we should remove them.

>  I am leaning towards discontinuing the meta package

What does that mean though?
People will be able to install it and get an old version of aiida. I don't think this is a solution.

We can give the `aiida-core>=1.0,<2.0` a try

**Comment by ltalirz** [comment]
I'll prepare a PR, we can discuss there

**Comment by ltalirz** [comment]
As discussed in #7, the plan is to keep it as a direct alias of `aiida-core`, mirroring each version.

Eventually, updating the meta package should be automated, similarly to how the conda-forge regro autotick bot works: https://github.com/regro/cf-scripts
